######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 15 17:17:01 2013
######################################################################

TEMPLATE = app
TARGET = bin/ringer
DEPENDPATH += . include src
INCLUDEPATH += . include
OBJECTS_DIR = obj

# Input
HEADERS += include/ring.hpp
SOURCES += src/ring.cpp src/ringer.cpp
